version: '3.9'

services:
  hoteldb:
    image: postgres
    networks:
      - hotel
    ports:
      - "5432:5432"
    volumes:
      - hoteldb:/var/lib/postgresql/data
      - ./create_db.sh:/docker-entrypoint-initdb.d/create_db.sh
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=hotel

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    networks:
      - hotel
    environment:
      PGADMIN_DEFAULT_EMAIL: admin_not_used@user.com
      PGADMIN_DEFAULT_PASSWORD: admin_not_used
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  maildev:
    container_name: maildev
    image: maildev/maildev
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - hotel

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /c/Users/35989/Desktop/comments/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - hotel

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - hotel
networks:
  hotel:

volumes:
  hoteldb:
  pgadmin_data:
