#scrape_configs:
#  - job_name: 'spring-boot-application'
#    scrape_interval: 15s
#    static_configs:
#      - targets: ['comments:8081']
#


scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

    static_configs:
      - job_name: 'comments_service'
      - targets: ['localhost:8081']
